name: Commented Pull Request

on:
  issue_comment:
    types:
      - created

jobs:
  pr_handler:
    name: Pull Request Handler
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@main

      - name: Pull Request Handler
        if: startsWith(github.event.comment.body, '/verify')
        uses: ScoopInstaller/GithubActions@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
