on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      force:
        description: "Enter 'force' if you want to force a refresh"
        required: false
        default: ""

name: Updates

jobs:
  excavate:
    name: Excavate
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Excavate
        uses: ScoopInstaller/GithubActions@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SKIP_UPDATED: 1

  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Update
        uses: foosel/scoop-checkver-action@main
        with:
          bucket: bucket
          force: ${{ github.event.inputs.force }}

      - run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          while read file; do
            if [[ $file == bucket/* ]] && [[ $file == *.json ]]; then
              version=$(cat $file | jq -r .version)
              manifest=$(basename $file .json)
              message="$manifest: Update to version $version"
              git add "$file"
              git commit -m "$message"
            fi
          done < <(git diff --name-only)

          git push
